"""model migration

Revision ID: 72a1c7ba88e7
Revises: bc8bfec60aa7
Create Date: 2024-07-28 13:07:09.625772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a1c7ba88e7'
down_revision = 'bc8bfec60aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_table('exhibits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exhibits'))
    )
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_review', sa.String(), nullable=True),
    sa.Column('artist', sa.Integer(), nullable=True),
    sa.Column('exhibit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['artists.id'], name=op.f('fk_installations_artist_artists')),
    sa.ForeignKeyConstraint(['exhibit'], ['exhibits.id'], name=op.f('fk_installations_exhibit_exhibits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installations')
    op.drop_table('exhibits')
    op.drop_table('artists')
    # ### end Alembic commands ###
