"""add columns

Revision ID: 750c241a0819
Revises: 70f636e46063
Create Date: 2024-07-31 10:06:16.040551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750c241a0819'
down_revision = '70f636e46063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_table('exhibits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exhibits'))
    )
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('exhibit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_installations_artist_id_artists')),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], name=op.f('fk_installations_exhibit_id_exhibits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installations')
    op.drop_table('exhibits')
    op.drop_table('artists')
    # ### end Alembic commands ###
